# Generated by Django 5.2.1 on 2025-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google')], default='email', help_text='Método de autenticación usado por el usuario', max_length=20),
        ),
    ]
