"""
Django settings for agronomia project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v0xy)8c+c%t91ztxz4vu7_hxmk8xt)kp@8jre$=h=z^mjt7%(*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Configuaracion de la pagina 

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #añadidas por el programador jijijiji

    #google autenticacion

    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    #Proveedores de Google
    'allauth.socialaccount.providers.google',
    'web',
    'chatbot',

]

#ID DE SITIO 
SITE_ID = 1


# agronomia/settings.py

AUTHENTICATION_BACKENDS = [
    # Necesario para el admin de Django
    'django.contrib.auth.backends.ModelBackend',
    
    # Autenticación específica de allauth (para login social, etc.)
    'allauth.account.auth_backends.AuthenticationBackend',
]





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'agronomia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # ← AGREGAR ESTA LÍNEA
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agronomia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






# Redirección después del login Y logout
LOGIN_REDIRECT_URL= '/'
LOGOUT_REDIRECT_URL = '/'


# Configuración del proveedor de Google
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # 'Informacion que se pedira a Google (perfil y email)
        'SCOPE': [
            'profile',
            'email',
        ],
        # 'AUTH_PARAMS' pedira si tiene varias cuentas o una xd
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# Configuración de cómo allauth maneja las cuentas
ACCOUNT_EMAIL_VERIFICATION = 'none' # No pedir verificación de email 
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False      # No pedimos un 'username', el email es suficiente
ACCOUNT_AUTHENTICATION_METHOD = 'email' # Permitir iniciar sesión escribiendo el email
SOCIALACCOUNT_LOGIN_ON_GET = True # no perdi permiso y django
