# Generated by Django 5.2.8 on 2025-11-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
